services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb_app
    ports:
      - "${NocoDB_HOST_PORT:-8080}:8080" # Use NocoDB_HOST_PORT from .env, default to 8080
    environment:
      # NC_DB_JSON: "${NC_DB_JSON}"
      # NC_DB: "${NC_DB}" # Commented out as we are using NC_DB_JSON
      NC_AUTH_JWT_SECRET: "${NC_AUTH_JWT_SECRET}"
      NC_TOOL_DIR: "/usr/app/data/"
      NC_PUBLIC_URL: "${NC_PUBLIC_URL}"
      NC_ADMIN_EMAIL: "${NC_ADMIN_EMAIL}"
      NC_ADMIN_PASSWORD: "${NC_ADMIN_PASSWORD}"
    volumes:
      - nocodb_data:/usr/app/data/
    depends_on:
      - postgres_db
    networks:
      - nocodb_network
    restart: unless-stopped

  postgres_db:
    image: postgres:15 # Or your preferred PostgreSQL version
    container_name: nocodb_postgres_db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql # Mounts the seed file
      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data
    networks:
      - nocodb_network
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432" # Expose PostgreSQL port to host if needed for external tools
    restart: unless-stopped


volumes:
  nocodb_data:
    driver: local
  postgres_data:
    driver: local

networks:
  nocodb_network:
    driver: bridge
